api:
  key: ""
  url: "https://api.currencybeacon.com/v1/convert"

server:
  port: 8080

spring:
  application:
    name: currency-converter
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: 
    password:
    url: jdbc:postgresql://localhost:5432/converter
  jpa:
    hibernate:
      ddl-auto: update