api:
  key: ${API_KEY:""}
  url: "https://api.currencybeacon.com/v1/convert"

server:
  port: 8080

spring:
  application:
    name: currency-converter
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/converter}
  jpa:
    hibernate:
      ddl-auto: update