version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build:
      context: .
    restart: always
    environment:
      - DB_HOST=db
    ports:
      - '8080:8080'
    depends_on:
      - db