version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ${POSTGRES_DATASTORE}:/var/lib/postgresql/data
    networks:
      - network

  api:
    build:
      context: .
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - DB_HOST=db
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - network
  
  webapp:
    build:
      context: ../webapp/.
    ports:
      - '4200:80'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}.0.0/16
          gateway: ${NETWORK}.0.1